version: "3.5"

services:
  client:
    volumes:
      - shared-volume-production:/data/public/images:rw
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: nginx -g "daemon off;"

  server:
    volumes:
      - shared-volume-production:/usr/share/nginx/html/images:rw
    env_file:
      - ./server/docker/production.env
    environment:
      NODE_ENV: production
    command: "npm start"

volumes:
  shared-volume-production: