version: "3.5"

services:
  client:
    command: nginx -g "daemon off;"
    volumes:
      - /srv/monumap-staging/images:/usr/share/nginx/html/images:rw

  server:
    env_file:
      - ./server/docker/staging.env
    environment:
      NODE_ENV: staging
    command: "npm start"
    volumes:
      - /srv/monumap-staging/images:/tmp/images:rw
